version: "3.1"
services:
  zenn-cli:
    build:
      context: ./CLI
    volumes:
      - ./articles:/zenn/articles
      - ./books:/zenn/books
    working_dir: /zenn
    ports:
      - 127.0.0.1:8001:8000
